version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8855:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M